export const listings = [
  {
    id: 1,
    name: "Buddy",
    breed: "Golden Retriever",
    vendor: "Sunrise Pets",
    price: 18500,
    date: "2026-04-11",
    status: "Approved",
    image: "https://images.pexels.com/photos/772891/pexels-photo-772891.jpeg?auto=compress&cs=tinysrgb&w=640",
    description: "Friendly and active retriever with full health check.",
  },
  {
    id: 2,
    name: "Luna",
    breed: "Siamese Cat",
    vendor: "Pet Palace",
    price: 15000,
    date: "2026-04-22",
    status: "Pending",
    image: "https://images.pexels.com/photos/617278/pexels-photo-617278.jpeg?auto=compress&cs=tinysrgb&w=640",
    description: "Loving indoor cat, excellent with families.",
  },
  {
    id: 3,
    name: "Max",
    breed: "French Bulldog",
    vendor: "Happy Tails",
    price: 24500,
    date: "2026-03-30",
    status: "Featured",
    image: "https://images.pexels.com/photos/356378/pexels-photo-356378.jpeg?auto=compress&cs=tinysrgb&w=640",
    description: "Calm companion dog with vaccination records.",
  },
  {
    id: 4,
    name: "Mia",
    breed: "Persian Cat",
    vendor: "Luxury Pets",
    price: 13200,
    date: "2026-05-02",
    status: "Rejected",
    image: "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=640",
    description: "Beautiful long-haired cat available for adoption.",
  },
]

export const transactions = [
  {
    id: "TXN-1001",
    avatar: "https://i.pravatar.cc/40?img=12",
    user: "Asha Mehta",
    serviceType: "Pet Food Order",
    amount: "₹1,250",
    method: "Card",
    status: "Completed",
    statusColor: "bg-emerald-100 text-emerald-700",
  },
  {
    id: "TXN-1002",
    avatar: "https://i.pravatar.cc/40?img=15",
    user: "Rahul Sharma",
    serviceType: "Vet Consultation",
    amount: "₹2,450",
    method: "UPI",
    status: "Pending",
    statusColor: "bg-amber-100 text-amber-700",
  },
  {
    id: "TXN-1003",
    avatar: "https://i.pravatar.cc/40?img=32",
    user: "Neha Singh",
    serviceType: "Grooming Session",
    amount: "₹980",
    method: "Card",
    status: "Refunded",
    statusColor: "bg-rose-100 text-rose-700",
  },
  {
    id: "TXN-1004",
    avatar: "https://i.pravatar.cc/40?img=7",
    user: "Suman Patel",
    serviceType: "Pet Boarding",
    amount: "₹5,800",
    method: "Netbanking",
    status: "Completed",
    statusColor: "bg-emerald-100 text-emerald-700",
  },
]

export const users = [
  {
    id: 1,
    name: "Ayesha Khan",
    email: "ayesha.khan@example.com",
    role: "Admin",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=9",
  },
  {
    id: 2,
    name: "Vikram Joshi",
    email: "vikram.joshi@example.com",
    role: "Vendor",
    status: "Active",
    avatar: "https://i.pravatar.cc/40?img=11",
  },
  {
    id: 3,
    name: "Rina Das",
    email: "rina.das@example.com",
    role: "Buyer",
    status: "Pending",
    avatar: "https://i.pravatar.cc/40?img=18",
  },
  {
    id: 4,
    name: "Karan Mehta",
    email: "karan.mehta@example.com",
    role: "Vendor",
    status: "Suspended",
    avatar: "https://i.pravatar.cc/40?img=22",
  },
]

export const bookings = [
  {
    pet: "Milo",
    breed: "Beagle",
    owner: "Priya Singh",
    email: "priya.singh@example.com",
    service: "Boarding",
    dates: "May 12 - 15",
    details: "3 days boarding with daily walks",
    status: "Pending",
    statusColor: "bg-amber-100 text-amber-700",
    serviceColor: "bg-violet-100 text-violet-700",
    action: "Approve",
    actionColor: "bg-indigo-600 text-white",
    avatar: "https://i.pravatar.cc/40?img=31",
  },
  {
    pet: "Lola",
    breed: "Shih Tzu",
    owner: "Amit Verma",
    email: "amit.verma@example.com",
    service: "Grooming",
    dates: "May 20",
    details: "Full grooming package",
    status: "Completed",
    statusColor: "bg-emerald-100 text-emerald-700",
    serviceColor: "bg-emerald-100 text-emerald-700",
    action: "",
    actionColor: "",
    avatar: "https://i.pravatar.cc/40?img=25",
  },
  {
    pet: "Zoe",
    breed: "Persian Cat",
    owner: "Neha Patel",
    email: "neha.patel@example.com",
    service: "Daycare",
    dates: "May 18 - 19",
    details: "Overnight daycare for 2 days",
    status: "Confirmed",
    statusColor: "bg-emerald-100 text-emerald-700",
    serviceColor: "bg-slate-100 text-slate-700",
    action: "",
    actionColor: "",
    avatar: "https://i.pravatar.cc/40?img=14",
  },
]

export const revenueData = [
  { month: "Jan", curr: 45, prev: 35, highlight: false },
  { month: "Feb", curr: 52, prev: 40, highlight: false },
  { month: "Mar", curr: 38, prev: 30, highlight: false },
  { month: "Apr", curr: 60, prev: 45, highlight: true },
  { month: "May", curr: 72, prev: 55, highlight: false },
  { month: "Jun", curr: 48, prev: 42, highlight: false },
  { month: "Jul", curr: 52, prev: 49, highlight: false },
  { month: "Aug", curr: 41, prev: 37, highlight: false },
]
